### ISSUE TITLE
clang-runtime package does not provide libc++.so libc++abi.so symlinks

### ISSUE THREAD

**Issue by korydraughn** [irods/externals#106]
- [x] master
- [x] 4-2-stable
---
Without the `libc++.so` symlink and `libc++abi.so` symlink, applications have to link against the library names with suffixes (e.g. `libc++.so.1`).
https://github.com/irods/externals/blob/475eaac31c7e37d2ada046d57e7d345f6aa1eef0/versions.json#L104-L121

**Comment by trel** [comment]
lines 113 and 115?   aren't those the symlinks?
