### ISSUE TITLE
pool.sks-keyservers.net is no more.

### ISSUE THREAD

**Issue by jbeal-work** [irods/externals#121]
https://sks-keyservers.net/status/ has

```
This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.

Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all.
```
I will do a pull request with a possible solution

**Comment by jbeal-work** [comment]
https://github.com/irods/externals/pull/122
https://github.com/irods/externals/pull/123

**Comment by trel** [comment]
thanks - confirmed to behave with MIT but only over TLS.... so hkps:// or https://      

what a find.   didn't know those were going away until they were gone... wild.

**Comment by trel** [comment]
appears MIT is slammed today, was getting intermittent success/failures with same requests.

**Comment by jbeal-work** [comment]
I have moved over to using curl from rvm.

**Comment by trel** [comment]
thanks again!
