### ISSUE TITLE
"make" with dependency problem

### ISSUE THREAD

**Issue by peggy0135** [irods/externals#124]
I was trying to do the porting on "Rocky Linux"
I have done the porting on centos8. So I referenced the experience.
but while I do the command "make".
I always stuck at "autoconf"
when I dump the log file
I am confused with the content below:
```
INFO - running: ['fpm', '-f', '-s', 'dir', '-t', 'not_detected', '-n', 'irods-externals-autoconf5ad3567c-0', '-m', '<packages@irods.org>', '--version', '1.0', '--vendor', 'iRODS Consortium', '--license', u'GPL v2', '--description', 'iRODS Build Dependency', '--url', 'https://irods.org', '-C', '/tmp/irods-externals/autoconf5ad3567c-0_src', u'opt/irods-externals/autoconf5ad3567c-0/bin', u'opt/irods-externals/autoconf5ad3567c-0/share'], unsafe_shell=False, check_rc=packaging failed, retries=0
INFO -   stdout: {:timestamp=>"2021-07-23T03:07:40.564739+0100", :message=>"Invalid output package (-t flag) type \"not_detected\". Expected one of: apk, cpan, deb, dir, empty, freebsd, gem, npm, osxpkg, p5p, pacman, pear, pkgin, pleaserun, puppet, python, rpm, sh, snap, solaris, tar, virtualenv, zip", :level=>:warn}
{:timestamp=>"2021-07-23T03:07:40.564825+0100", :message=>"Fix the above problems, and you'll be rolling packages in no time!", :level=>:fatal}
INFO -   stderr: 
INFO - 
ERROR - packaging failed
Building [autoconf]
```
Is there any hint about it, or I misunderstand something in doc or comment in source code?
Thank you

**Comment by trel** [comment]
The 'system detection' hasn't been taught about RockyLinux yet...  see the 'not_detected' in the output...

This logic needs to be updated to 'catch' and treat RockyLinux as 'rpm':
https://github.com/irods/externals/blob/bab66c318c3e0a068bafc071d35dc3b89f66aae7/build.py#L146-L157

**Comment by peggy0135** [comment]
thank you
I fixed it by add my platform to the list.
it's building the packages now

**Comment by trel** [comment]
Excellent - happy to have a pull request if you'd like.

Rocky Linux is probably going to be officially supported in the future and community submissions are always welcome.

**Comment by peggy0135** [comment]
thank you
I will try to organize my modification and submit it.

**Comment by peggy0135** [comment]
Hi @trel,
I had modified the scripts and test them both on CentOS 8.4 and Rocky Linux 8.4
