### ISSUE TITLE
build error in Rocky Linux

### ISSUE THREAD

**Issue by peggy0135** [irods/externals#149]
I followed the "readme"
 but when I do "make"
 it stuck at something about AWS, showed as below

INFO -   stderr: In file included from /tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSErrorMarshaller.cpp:21:
/tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/client/AWSError.h:51:13: error: definition of implicit copy assignment operator for 'AWSError<Aws::Client::CoreErrors>' is deprecated because it has a user-provided copy constructor [-Werror,-Wdeprecated-copy-with-user-provided-copy]
            AWSError(const AWSError<CoreErrors>& rhs) :
            ^
/tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSErrorMarshaller.cpp:93:23: note: in implicit copy assignment operator for 'Aws::Client::AWSError<Aws::Client::CoreErrors>' first required here
                error = Marshall(StringUtils::Trim(codeNode.GetText().c_str()),
                      ^
1 error generated.
make[3]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/build.make:242: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/AWSErrorMarshaller.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:20:
/tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/client/AWSError.h:51:13: error: definition of implicit copy assignment operator for 'AWSError<Aws::Client::CoreErrors>' is deprecated because it has a user-provided copy constructor [-Werror,-Wdeprecated-copy-with-user-provided-copy]
            AWSError(const AWSError<CoreErrors>& rhs) :
            ^
/tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:592:15: note: in implicit copy assignment operator for 'Aws::Client::AWSError<Aws::Client::CoreErrors>' first required here
        error = AWSError<CoreErrors>(CoreErrors::NETWORK_CONNECTION, "", "Unable to connect to endpoint", true);
              ^
1 error generated.
make[3]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/build.make:227: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/AWSClient.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:213: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
make[1]: *** [Makefile:136: all] Error 2
In file included from /tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:20:
/tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/client/AWSError.h:51:13: error: definition of implicit copy assignment operator for 'AWSError<Aws::Client::CoreErrors>' is deprecated because it has a user-provided copy constructor [-Werror,-Wdeprecated-copy-with-user-provided-copy]
            AWSError(const AWSError<CoreErrors>& rhs) :
            ^
/tmp/irods-externals/aws-sdk-cpp1.4.89-1_src/aws-sdk-cpp/aws-cpp-sdk-core/source/client/AWSClient.cpp:592:15: note: in implicit copy assignment operator for 'Aws::Client::AWSError<Aws::Client::CoreErrors>' first required here
        error = AWSError<CoreErrors>(CoreErrors::NETWORK_CONNECTION, "", "Unable to connect to endpoint", true);
              ^
1 error generated.
make[3]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/build.make:227: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/client/AWSClient.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:213: aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2
make[1]: *** [Makefile:136: all] Error 2
INFO - 
ERROR - build failed
Building [aws-sdk-cpp]

Is there any tips or hint, that can solve this problem?
Thank you

**Comment by trel** [comment]
I think this is just due to us not getting all the externals cleaned up quite yet on the main branch.

We know that `make package` is working... this is the subset of software in externals needed to build the server and the icommands.

The rest (including aws-sdk-cpp) will be getting up to speed soon.

**Comment by korydraughn** [comment]
all externals packages build successfully now that #154 is merged.

@peggy0135 please give it another try and let us know how it goes.

**Comment by peggy0135** [comment]
hi , thank you, it looks ok and built successfully.
I will keep try the following steps with other packages.

**Comment by korydraughn** [comment]
Excellent!

If you encounter other problems, please open a new issue.
