### ISSUE TITLE
Build error in Ubuntu 18.04

### ISSUE THREAD

**Issue by xkdzml** [irods/externals#151]
Hi I'm new to Linux.

I'm currently using Ubuntu 18.04. and struggling to install irods.

I followed (this) [https://docs.irods.org/4.2.3/getting_started/installation/#non-package-install-run-in-place] documentation, in 'Non-Package Install (Run In Place)' section.

I've successfully executed four commands ([1] ~ [4]).

[1]   user@hostname:~ / $ export IRODS_EXTERNALS=/tmp/irods-externals
[2]   user@hostname:~ / $ git clone https://github.com/irods/externals $IRODS_EXTERNALS
[3]   user@hostname:~ / $ cd $IRODS_EXTERNALS
[4]   user@hostname:/tmp/irods-externals $ ./install_prerequisites.py
[5]   user@hostname:/tmp/irods-externals $ make

but while executing 'make', I found that I cannot proceed anymore.

I've searched for a week to get solution or to find something that I've might missed, but still the problem is not solved.

here is my error message while I'm building irods

```error
root@syslab:/mnt/install_irods/externals# make -j 16
./build.py -v aws-sdk-cpp > aws-sdk-cpp.log 2>&1
./build.py -v elasticlient > elasticlient.log 2>&1
./build.py -v mungefs > mungefs.log 2>&1
./build.py -v qpid-proton > qpid-proton.log 2>&1
Makefile:154: recipe for target 'irods-externals-mungefs1.0.4-0_1.0~bionic_amd64.deb' failed
make: *** [irods-externals-mungefs1.0.4-0_1.0~bionic_amd64.deb] Error 1
make: *** Waiting for unfinished jobs....
Makefile:186: recipe for target 'irods-externals-qpid-proton0.23.0-0_1.0~bionic_amd64.deb' failed
make: *** [irods-externals-qpid-proton0.23.0-0_1.0~bionic_amd64.deb] Error 2
Makefile:98: recipe for target 'irods-externals-elasticlient0.1.0-2_1.0~bionic_amd64.deb' failed
make: *** [irods-externals-elasticlient0.1.0-2_1.0~bionic_amd64.deb] Error 2
Makefile:34: recipe for target 'irods-externals-aws-sdk-cpp1.4.89-1_1.0~bionic_amd64.deb' failed
make: *** [irods-externals-aws-sdk-cpp1.4.89-1_1.0~bionic_amd64.deb] Error 2
```

thank you for reading my issue.

**Comment by trel** [comment]
Hi @xkdzml,

Sorry for the trouble - yes, most people are not building their own externals and so we've not spent as much time keeping that documentation as polished for multiple releases.

- I recommend looking at 4.2.11 documentation - it's mostly the same as 4.2.3 (linked), but some things have moved.
- make sure you're building the 4-2-stable branch (`git checkout 4-2-stable`)
- no need for `make -j` - each build target is already parallelized, and the dependencies themselves are defined in the Makefile
- you can try `make server` first.. this subset of targets are the requirements for the irods-server.  additional plugins may require some of the other make targets.

As a separate approach, consider a regular packaged install first, to see what success would look like.   Building everything from source is definitely a tough first leap.

**Comment by trel** [comment]
Closing - this works as expected.   No action necessary.
