### ISSUE TITLE
.yum.repo files construct bad baseurl for rocky/alma/ubi

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/externals#169]
For packages, core-dev, and unstable, the provided .yum.repo files construct a bad baseurl for rocky/alma/ubi.

For example, the .yum.repo file for unstable contains:
```
baseurl=https://unstable.irods.org/yum/pool/centos$releasever/$basearch
```
`centos$releasever` is the problematic bit.

It works fine for centos 7; but for almalinux 8, rocky linux 8, and ubi8, it turns into `centos8`, which does not match the `el8` subdirectory we use.

**Comment by trel** [comment]
should we have a separate `.yum.repo` file?   seems the easiest, just additional README.

**Comment by SwooshyCueb** [comment]
Sounds good to me

**Comment by trel** [comment]
I've created two aliases in core-dev, unstable, and packages.irods.org for el6 and el7...

```
ln -s centos6 el6
ln -s centos7 el7
```

and updated the `yum.repo` file accordingly...
```diff
- baseurl=https://unstable.irods.org/yum/pool/centos$releasever/$basearch
+ baseurl=https://unstable.irods.org/yum/pool/el$releasever/$basearch
```

I've confirmed the alias works for the older distribution, and now works with `el8` as well.

I will await confirmation from other(s) before closing.

**Comment by trel** [comment]
Oh, and no new/different README required.   Same instructions as in the past.

**Comment by SwooshyCueb** [comment]
I couldn't find any documentation about `$releasever` and `$basearch` with `dnf`, so I just double-checked that they work on rockylinux:8:
```
Python 3.6.8 (default, Nov  9 2021, 14:44:26) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dnf
>>> db = dnf.dnf.Base()
>>> db.conf.substitutions
{'arch': 'x86_64', 'basearch': 'x86_64', 'releasever': '8'}
```

I think we're good.

**Comment by trel** [comment]
nice.   thanks.
