### ISSUE TITLE
Remove `cpr` externals package

### ISSUE THREAD

**Issue by korydraughn** [irods/externals#172]
With this PR merged, https://github.com/irods/irods_capability_indexing/pull/123, the `cpr` externals package is no longer needed and should be removed.

https://github.com/irods/externals/blob/a00fced725340b48798cf9059a33cfce03c05fc6/versions.json#L157-L176
https://github.com/irods/externals/blob/a00fced725340b48798cf9059a33cfce03c05fc6/Makefile#L1
https://github.com/irods/externals/blob/a00fced725340b48798cf9059a33cfce03c05fc6/Makefile#L89-L95
https://github.com/irods/externals/blob/a00fced725340b48798cf9059a33cfce03c05fc6/Makefile#L209

**Comment by SwooshyCueb** [comment]
Yes please!

**Comment by trel** [comment]
Oh... so... does our `elastic` require this?   Or just that we also need to remember to remove that singular usage of `TEMPLATE_CPR_RPATH` in the `build_steps`?

**Comment by korydraughn** [comment]
Elastic comes with cpr. We have to update all references to point at elastic's cpr.

**Comment by korydraughn** [comment]
Is there a commit/PR we can link to to capture the reason for closing this?

**Comment by SwooshyCueb** [comment]
#193
