### ISSUE TITLE
20.04 Ubuntu LTS Build Failure (clang: wrong gcc default)

### ISSUE THREAD

**Issue by JackJHarris** [irods/externals#179]
# Issue Description 

Clang fails to build under a fresh instance of Ubuntu 20.04 LTS 

`error: a destructor cannot be ‘constexpr’`

-- it appears as the the default g++ version 9 may not work according to this

https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg52843.html

Default version in Ubuntu 20.04 is 9.4.0
```
gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

# Manual Fix (allows clang to build successfully)

1. Ensure gcc-10 is there
`sudo apt-get install gcc-10 g++-10` 

Which was already installed:
```
g++-10 is already the newest version (10.3.0-1ubuntu1~20.04).
gcc-10 is already the newest version (10.3.0-1ubuntu1~20.04).
```
as part `install_prerequisites.py`
     ```
        elif distro_major_version == '20':
            # Compiling LLVM 13's libcxx requires at least GCC 10.
            cmd.extend(['gcc-10', 'g++-10'])
      ```  
     but since it isn't set as a the default and gcc-9 is still used
     
2. Make gcc-10 the default (higher priority)

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 20
```

# Suggested fix

- [ ] Add `update-alternatives` as part of `install_prerequisites.py`

Or

- [ ] Warn that this needs to be done at the end of  `install_prerequisites.py` when gcc-9 is default

**Comment by trel** [comment]
This is part of the readme...   Do those instructions need updating?

https://github.com/irods/externals#ubuntu-18-ubuntu-20-and-debian-11

**Comment by JackJHarris** [comment]
Ah, that documentation has it! --- I was using this documentation:

`https://docs.irods.org/4.3.0/getting_started/installation/#input-file-for-catalog-service-consumer`

which doesn't mention that there could be any distro-specific configurations needed

```
...
user@hostname:/tmp/irods-externals $ ./install_prerequisites.py
user@hostname:/tmp/irods-externals $ make
```

So, maybe the other docs need to say something like -- see README for distro-specific installation instructions -- or if the update-alternatives part was automagical then it could be closer to universal -- either way

**Comment by trel** [comment]
fair fair.    most are not building from source, so it has not been as scrutinized.

**Comment by trel** [comment]
I think since the shell ('out here') itself needs to be updated, we cannot do the work *inside* install_prerequisites.py - hence the README-based solution at the moment.   I've updated the docs to point to the externals repo for platform-specific instructions.

**Comment by trel** [comment]
Now linked - I think the reason we couldn't put the magic in the python script is because it needs to affect the shell that is running the make command.
