### ISSUE TITLE
libs3: Build fails with `format-overflow` warning on almalinux:9

### ISSUE THREAD

**Issue by alanking** [irods/externals#185]
This warning was added in gcc 7 at the latest and yet I have not seen it trip on any platforms until now.

I'm using `gcc-toolset-12` because `gcc-toolset-11` is not available in repos currently configured.

From the log...
```
INFO -   stderr: src/s3.c: In function ‘listBucketCallback’:
src/s3.c:1230:35: error: ‘%4llu’ directive writing between 4 and 17 bytes into a region of size 16 [-Werror=format-overflow=]
 1230 |                 sprintf(sizebuf, "%4lluK",
      |                                   ^~~~~
src/s3.c:1230:34: note: directive argument in the range [0, 18014398509481983]
 1230 |                 sprintf(sizebuf, "%4lluK",
      |                                  ^~~~~~~~
src/s3.c:1230:17: note: ‘sprintf’ output between 6 and 19 bytes into a destination of size 16
 1230 |                 sprintf(sizebuf, "%4lluK",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
 1231 |                         ((unsigned long long) content->size) / 1024ULL);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [GNUmakefile:222: build/obj/s3.o] Error 1
make[1]: *** Waiting for unfinished jobs....
INFO -          
ERROR - build failed
Building [libs3]
```

**Comment by alanking** [comment]
This may warrant an issue in the libs3 repo, but figured I'd start here.

**Comment by korydraughn** [comment]
It appears that gcc is detecting potential overflow, so I think you're correct that an issue should be created.

At least so we're aware of it.

**Comment by alanking** [comment]
Okay, I created https://github.com/irods/libs3/issues/26 to track the issue in the libs3 repo. We can determine here whether we can ignore this warning for our purposes and use the other issue to address the problem.

**Comment by korydraughn** [comment]
Maybe.

Does the warning appear if you use `sprintf` correctly?
Does the warning appear if you use `snprintf`?
What happens if `content->size` is -1? _(Assuming it is an `int`)_

This has likely existed for several years now. And given there hasn't been any updates to the upstream repo, it is likely safe to say we own it now. Meaning we can fix the warning. The question then becomes, how do we test it?

**Comment by alanking** [comment]
> Does the warning appear if you use `sprintf` correctly?

Sorry, I don't understand. Is `sprintf` being used incorrectly?

>  Does the warning appear if you use `snprintf`?

I would think not. That would be my suggested solution to https://github.com/irods/libs3/issues/26.

>  What happens if `content->size` is -1? (Assuming it is an `int`)

`content->size` is not an `int`, it is `uint64_t`. An underflow results in a positive value that is larger than 1024 * 1024.

**Comment by alanking** [comment]
> I don't think it is being used incorrectly, but perhaps increasing the size of sizebuf resolves the warning. We give sprintf a buffer of size 16, and the compiler seems to be warning us that the buffer is too small to hold the full range of the type.

Fair enough. Can try that as well.

**Comment by alanking** [comment]
irods/libs3#26 is now resolved. This can be resolved by bumping the sha.

**Comment by korydraughn** [comment]
Let's go ahead and take care of that.
