### ISSUE TITLE
Makefile: cpr package depends on elasticlient package; this should be reversed

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/externals#192]
The Makefile declares that elasticlient is a build dependency of cpr:
https://github.com/irods/externals/blob/main/Makefile#L81

However, it's actually elasticlient that uses CPR, not the other way around.

**Comment by trel** [comment]
well that's a bit upside-down.    and surprising.

**Comment by SwooshyCueb** [comment]
Superseded by irods/irods_capability_indexing#128
