### ISSUE TITLE
Provide a means of setting package revision for in-place upgrades

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/externals#219]
At present, we have no means of updating a package in-place. The closest thing we have to a package revision number is `consortium_build_number`, which is not part of the package version number, but part of the package name and subdirectory.

**Comment by korydraughn** [comment]
Does **updating a package in-place** mean reusing existing build artifacts + the revision number to produce a new package?

**Comment by SwooshyCueb** [comment]
No.

Presently, all our packages are version `1.0` for EL distros and `1.0~[codename]` for deb-based distros. We have no way to produce a package with a different version number. Any update to a package will produce a whole new package with a different package name. This new package can be installed side-by-side with the previous version of the package. While we do have a need for side-by-side installs of different versions of our externals, it would behoove us to provide a means of updating an existing package.

A couple of times in recent-ish memory when this would've been useful:
- When we had to update nanodbc to package dependency declarations
- When we had to update clang-runtime to include a non-versioned symlink to libc++

With proper package revisions, the package version numbers will be `1.0-[rev].el[el_ver]` for EL distros and `1.0-[rev]~[codename]` for deb-based distros.

**Comment by korydraughn** [comment]
So would the package with the revision number replace the existing package?

Correct me if I'm wrong, but it sounds like you're saying we're stuck with `1.0` for legacy reasons and the `[rev]` component gives us a way to tweak things (e.g. add a symlink w/o changing the binaries).

Another question - is the `[rev]` component standardized/a-common-convention for DEBs and RPMs?

> This new package can be installed side-by-side with the previous version of the package.

I'm assuming this gives you more flexibility in influencing the behavior of the packaging system?

**Comment by SwooshyCueb** [comment]
> Correct me if I'm wrong, but it sounds like you're saying we're stuck with `1.0` for legacy reasons and the `[rev]` component gives us a way to tweak things (e.g. add a symlink w/o changing the binaries).

That's correct.

> Another question - is the `[rev]` component standardized/a-common-convention for DEBs and RPMs?

Yes, one we already use for our non-externals packages.

> So would the package with the revision number replace the existing package?

A higher revision string will replace a lower revision number. The absence of a revision string is equivalent to a revision string of `0`.

> > This new package can be installed side-by-side with the previous version of the package.
> 
> I'm assuming this gives you more flexibility in influencing the behavior of the packaging system?

In that quote I am trying to describe the current behavior of the externals package builder and the results of the current behavior.
