### ISSUE TITLE
Missing comma in `install_prerequisites.py`

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/externals#234]
This list item in `install_prerequisites.py` is missing a trailing comma:
https://github.com/irods/externals/blob/68cdd688f22f4ac7e3974aa1f0c7bf980b21df4f/install_prerequisites.py#L110
This causes the script to fail on EL.

**Comment by korydraughn** [comment]
Does this affect the 4.3.2 release? If so, how?

**Comment by SwooshyCueb** [comment]
Kinda.
It prevents building the externals builder dev environment images for EL. Without the images, the updated externals pacakges from #233 can't be built. The updated externals packages are needed for the audit plugin, and maybe other things as well.
