### ISSUE TITLE
Update commitish on `jwt-cpp`

### ISSUE THREAD

**Issue by MartinFlores751** [irods/externals#255]
In order for irods/irods_client_http_api#344 to compile, jwt-cpp needs to have it's commitish updated to one of the latest commits.

The PR referenced was tested with jwt-cpp on the latest commit on master.

**Comment by korydraughn** [comment]
What version of jwt-cpp did you test the HTTP API against?

**Comment by MartinFlores751** [comment]
I ended up testing on tip of jwt-cpp master branch.
For testing, my cmake FetchContent_Declare had `GIT_TAG master`.

**Comment by korydraughn** [comment]
Ok. Let's pick a stable version that meets the requirements and run the tests. Let us know if they pass and update the PRs accordingly.

**Comment by MartinFlores751** [comment]
The last tagged release is 0.7.0, released December '23. The minimum required commit that has everything needed is from August '24. Tip of main is two commits ahead of min required.

Did you want me to pick the minimum required commit?

**Comment by trel** [comment]
Interesting.    We've done this before (packaged a not-yet-released committish ... perhaps for libs3).

**Comment by korydraughn** [comment]
If tip of main doesn't provide anything worth including (e.g. bug fixes, etc), then let's go with the minimum required commit.

As long as you can prove the HTTP API PR works as intended and doesn't crash or fall over, I think we're good.

**Comment by korydraughn** [comment]
The primary requirement is that it doesn't crash the HTTP API.
