### ISSUE TITLE
Consider adding jsoncons library as an externals package

### ISSUE THREAD

**Issue by korydraughn** [irods/externals#257]
Adding the jsoncons library to the iRODS 5 PR results in 155 files being added to the repo. See the following:
- https://github.com/irods/irods/pull/7988

It is guaranteed that the HTTP API and the S3 API will also be updated to use the library for configuration validation in the future (unless we decide to go in a different direction).

To avoid duplicating these files across repos, we need to consider providing the library as an externals package.

Additional Info:
- jsoncons does not appear to be available via OS package managers
  - I used pkgs.org and only considered the platforms we support
- jsoncons does not appear to support picking/copying a subset of the extensions
  - This isn't important if we provide an externals package

**Comment by trel** [comment]
this makes sense to me.

**Comment by SwooshyCueb** [comment]
I am in favor of an externals package for this. I've looked into alternatives that are in distro repos and have found them all lacking.

**Comment by korydraughn** [comment]
Ok. Let's do it.

**Comment by korydraughn** [comment]
@SwooshyCueb Please close if completed.
