### ISSUE TITLE
Building mungefs needs boost included

### ISSUE THREAD

**Issue by bh9** [irods/externals#33]
mungefs depends on boost, but versions.json doesn't include instructions to include the correct boost files. The cmake call needs to also have `-I TEMPLATE_BOOST_ROOT/include` (or some other template variable that does the same thing)

**Comment by alanking** [comment]
What branch/SHA and OS are you building against? I have successfully built all externals on ubuntu:16.04 and centos:7 docker images using the steps in the readme. I did have to install sudo, python, git, and curl first.

**Comment by bh9** [comment]
4-2-stable, Ubuntu 12.04 (the shame, I know, but we still have some in production)
Side note: if you had to install sudo, python, git and curl first, could you add a line to the README which installs them please?

**Comment by trel** [comment]
- a note about `sudo` and `python` makes sense.

- `git` is already installed by `install_prerequisites.py`, but might be noted as its the easiest way to get this repo into a container in the first place.

- `curl` should be added to the list(s) within `install_prerequisites.py`.

- Ubuntu12 requires a newer g++ to build cmake and clang.  That functionality should be restored from https://github.com/irods/externals/commit/e08ee1884547c9dd26d2a0ba7045051c453dcf83

**Comment by trel** [comment]
mungefs needs fuse 2.9.1 or greater... see https://github.com/irods/mungefs/issues/11

**Comment by trel** [comment]
I think we can close this?   What else is needed?

**Comment by trel** [comment]
closing as fixed.   please open a new issue if other tweaks need to be made.
