### ISSUE TITLE
install_prerequisites doesn't handle its own dependencies cleanly

### ISSUE THREAD

**Issue by mcv21** [irods/externals#4]
install_prerequisites needs the following things installed which are not part of build-essential on ubuntu12 (at least):

python-simplejson
software-properties-common
sudo

The first 2 it could just install if they were absent; in the latter case, it should either be happy to be run as root (e.g. for people building in a chroot) or detect the lack of sudo and produce a neat error message.

**Comment by trel** [comment]
thanks for the report - i'm not sure how to make this much better.  i've updated the readme to state the need for sudo and python and things build cleanly on newer OSs now.   closing.
