### ISSUE TITLE
Which commit on 4-2-stable should be used to build iRODS 4.2.7?

### ISSUE THREAD

**Issue by kjsanger** [irods/externals#42]
Which commit on the `4-2-stable` branch is the correct one to build iRODS `4.2.7`? The `HEAD` doesn't appear to be compatible any more, which may be expected as I guess that's targeted at `4.2.8+`. There are a number of commits that work, but it's not clear which is preferred, or correct.

Please consider tagging  `4-2-stable` with the corresponding release number. It would be very helpful when reproducing a build.

Thanks.

**Comment by trel** [comment]
Until now, it hasn't been a goal to keep the externals buildable for any particular iRODS release.  We have been targeting/optimizing the use case of getting built packages into our apt/yum repositories, to remove the requirement of from-scratch full source builds.

We will probably have to create branches/commits in this repository to provide the specific versions named in the CMakeLists.txt file for a particular iRODS release tag.

Example for current `4-2-stable`:
   https://github.com/irods/irods/blob/4-2-stable/CMakeLists.txt#L30-L38

We will look at 4.2.7 first, and then start to go back in time.

**Comment by trel** [comment]
This appears the one we want:
  91003d0ab3a8e66707339cfca1d395b81e5c4ef2

Please confirm, and we will tag it 4.2.7.

If it's not quite enough/right, we will branch from there and tag after any required tweaks.

**Comment by kjsanger** [comment]
Yes, that's the one I tried and built 4.2.7 successfully against it.

**Comment by trel** [comment]
Excellent - thanks - tag coming soon.

**Comment by trel** [comment]
It is done - https://github.com/irods/externals/releases
