### ISSUE TITLE
libs3 fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by korydraughn** [irods/externals#46]
Output from docker container: [libs3.log](https://github.com/irods/externals/files/4333542/libs3.log)

All other packages were built successfully (qpid-with-proton required that rsync be installed).

This was done using externals w/ the nanodbc + fmt PR.

**Comment by alanking** [comment]
irods/libs3#3 has resolved this. I will bump the SHA to point at the new SHA. I'm also going to change the version_string to point at the branch rather than the SHA so that it stops moving around. Thoughts @trel?

**Comment by trel** [comment]
you mean the other way around?   pointing at the branch can allow it to move...

**Comment by alanking** [comment]
Currently we have:
https://github.com/irods/externals/blob/76492cc53b73b98f5f4301ddb6017427dc085fde/versions.json#L305-L307

Here are the options:

1.
```json
        "commitish": "59b6237135126e53690a41a2baba74c092304c21",
        "version_string": "59b62371",
```
2.
```json
        "commitish": "59b6237135126e53690a41a2baba74c092304c21",
        "version_string": "v4",
```
3.
```json
        "commitish": "v4",
        "version_string": "v4",
```
4.
```json
        "commitish": "v4",
        "version_string": "59b62371",
```

I was proposing option 2 above, but I am not married to the idea. Also, it is unclear to me what the consortium_build_number should be changed to (increment by 1?).

**Comment by trel** [comment]
We go with option 1 - there is no upside to us releasing a tag as far as I can tell.

The consortium_build_number should be 0 for the first 'packaging' of a particular SHA.  If the Consortium goofs or needs to build the same SHA a different way, then we increment that value.
