### ISSUE TITLE
add cpr and elasticlient for indexing and publishing capabilities

### ISSUE THREAD

**Issue by trel** [irods/externals#55]
- [x] master
- [x] 4-2-stable

**Comment by trel** [comment]
master was included in 747f4f86e594165631fe2642976b110448107b79 and 7478c2afc29716e099491a67e8f386cf7c31eb3f

**Comment by trel** [comment]
oops, there's still a PR open (#26)

**Comment by d-w-moore** [comment]
reopening on the minor matter of porting the elasticlient consortium build number bump ("0" -> "1") from master to 4-2-stable.  

No major concerns here , it's all good news; master tested 100% good and all indexing/elasticlient changes to the present work (working thru the slide demo manually) in master branch , on Cen7, with the lib64/ - to -lib/ move in force as well.

**Comment by d-w-moore** [comment]
Do we have an imperative to change the lib64 thing in elasticlient, on 4-2-stable? If  it's not important, we can close this again.... Just depends how much we want  4-2-stable and master looking the same.

**Comment by d-w-moore** [comment]
Ref. https://github.com/irods/irods_capability_indexing/issues/23

**Comment by trel** [comment]
yes, please make 4-2-stable as correct and good as possible.   once we release with this version, we won't bump it again until we need to (security or feature needed).
