### ISSUE TITLE
fmt externals package is missing the lib directory on Centos

### ISSUE THREAD

**Issue by korydraughn** [irods/externals#64]
- [x] master
- [x] 4-2-stable
---
fmt stores the built shared libraries under `lib64` instead of `lib`.

Adding `CMAKE_INSTALL_LIBDIR=lib` to the cmake step fixes the issue.

4-2-stable of irods/irods cannot be built in CI without this fix.

**Comment by trel** [comment]
this will require setting `"consortium_build_number": "1",`, since it's the same SHA of the upstream code.

please take a similar look at aws-sdk-cpp and elasticlient

**Comment by korydraughn** [comment]
The 4-2-stable branch handles this for `elasticlient` and `cpr` by renaming `lib64` to `lib`. That was my original solution too until i found this cmake option.

So I think `aws` is the only other package that does not properly handle the `lib64` directory.
