### ISSUE TITLE
install_prerequisites should not change system default compiler

### ISSUE THREAD

**Issue by mcv21** [irods/externals#7]
At least on ubuntu12, install_prerequisites uses update-alternatives to change gcc and g++.

It should not do this - building software shouldn't be modifying system-wide defaults like this (for one thing, consider what would happen if everyone did it); instead it should tell the user what environment and/or command-line arguments to set so that the subsequent builds will work.

**Comment by trel** [comment]
We're assuming at this time this repository is being built in a container or VM.

This was a design decision - we're optimizing for building externals ourselves and sharing the resulting packages via apt and yum.
