### ISSUE TITLE
Incorrect top-level directory for spdlog package

### ISSUE THREAD

**Issue by korydraughn** [irods/externals#73]
The following line causes the spdlog files to be installed with an incorrect directory structure. This makes building the master branch of `irods/irods` impossible.
https://github.com/irods/externals/blob/ccaaf045d754a87c081aaf2e4e7a1122b128dfc1/versions.json#L413

## Solution
Change `cp -r include/spdlog/*` to `cp -r include/spdlog`.

**Comment by trel** [comment]
i think this means we'll need to bump it to the consortium_build_number to 1, as it's already been built and published once.

**Comment by trel** [comment]
can use this same issue number for that

**Comment by korydraughn** [comment]
Ok
