### ISSUE TITLE
install_prerequisites should ask for permission or ask the admin to do the installs

### ISSUE THREAD

**Issue by mcv21** [irods/externals#8]
Currently, the operation of install_prerequisites is rather opaque, and it makes quite significant changes to the system. It should either tell the user what it proposes to do and ask for permission, or tell the user what they need to do.

For instance, if the `apt-get install` command didn't have `-y`, then the user would get told what set of packages were about to be installed. Or a message of the form "please do apt-get install [packages]" could be emitted.

**Comment by trel** [comment]
We're assuming at this time this repository is being built in a container or VM.

This was a design decision - we're optimizing for building externals ourselves and sharing the resulting packages via apt and yum.
